### ISSUE TITLE
[Dark Mode] Shadow colors should not be inverted with other elements

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#90]
**Describe the bug**
Author profile image shadow colors invert to white while on dark mode.

**To Reproduce**
1. Go to homepage
2. See error

**Expected behavior**
The shadow color should stay gray/black, but still be visible.

**Screenshots**
![screenshot_2018-07-28 extum material theme demo 3](https://user-images.githubusercontent.com/17576065/43356436-5d46d55e-9279-11e8-87f7-517dc3b8641b.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Version 0.1.0-beta.7

**Additional context**
This does need discussion as it may have changes in the future.

**Comment by ghost** [comment]
I like it. It looks pretty cool but, I can change this.

**Comment by ardacebi** [comment]
@Nathan2023 I specifically marked it as needs discussion. I also like it this way, but if we agree on doing this, we will need to change all shadows to be like this.

And I'm not sure whether it's OK with the guidelines. Can you check real quick?

**Comment by ardacebi** [comment]
@Nathan2023 What does the guidelines say about this?

**Comment by hammerhai** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.

### Preparedness/Guidelines
_Extum Material_ is set to have it's own settings page with a dedicated "Adaptive Mode." **Based on guidelines, shadows are supposed to stay dark even if the theme changed to dark/night/adaptive/light.**
